# Install script for directory: /home/huynhtai/tmp/zephyrproject/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/home/huynhtai/Downloads/ebook_RTOS/Zephyr_SDK/arm-zephyr-eabi/bin/arm-zephyr-eabi-objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/arch/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/lib/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/soc/arm/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/boards/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/subsys/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/drivers/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/cmsis/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/atmel/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/altera/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/canopennode/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/civetweb/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/esp-idf/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/fatfs/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/cypress/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/infineon/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/nordic/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/openisa/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/nuvoton/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/microchip/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/silabs/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/st/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/stm32/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/ti/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/libmetal/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/lvgl/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/mbedtls/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/mcumgr/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/nxp/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/open-amp/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/loramac-node/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/openthread/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/segger/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/tinycbor/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/tinycrypt/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/littlefs/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/mipi-sys-t/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/nrf_hw_models/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/xtensa/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/modules/tfm/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/kernel/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/cmake/flash/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/cmake/usage/cmake_install.cmake")
  include("/home/huynhtai/tmp/zephyrproject/blinky_stm32/zephyr/cmake/reports/cmake_install.cmake")

endif()

